export enum Modals {
    HAS_TEMPLATE = "HAS_TEMPLATE",
    VALIDATION_ERRORS = "VALIDATION_ERRORS",
    SUCCESS_REGISTRATION = "SUCCESS_REGISTRATION",
    LOGOUT_CONFIRM = "LOGOUT_CONFIRM",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    TEST_PREVIEW = "TEST_PREVIEW",
    CONFIRM_END_OF_TEST = "CONFIRM_END_OF_TEST"
}